### ISSUE TITLE
how do we add a calendar or daterange picker?

### ISSUE THREAD

**Issue by adgfx** [bootscore/bs-contact-form-7#5]
I am trying to add a appointment booking form, needed a daterange picker in the form.

**Comment by crftwrk** [comment]
Use Contact Form 7 date field `[date date-407 class:form-control]`. https://contactform7.com/date-field/

![screenshot](https://user-images.githubusercontent.com/51531217/169089323-3cb1a7d6-5406-4e41-aff2-7f0d4b8c405b.png)

<img width="428" alt="Bildschirmfoto 2022-05-18 um 18 04 02" src="https://user-images.githubusercontent.com/51531217/169089585-a6697b03-f3c7-4a5b-9566-db18e4f49deb.png">

Note that a date-picker is not supported by Bootstrap. You must style it by yourself.

Solved?

**Comment by crftwrk** [comment]
Haven't heard anything here for a while. Close the issue now.
