### ISSUE TITLE
[BUG] checkbox gets wrong classes on span with class wpcf7-form-control 

### ISSUE THREAD

**Issue by joworeiter** [bootscore/bs-contact-form-7#8]
Adding a second checkbox, beneath a acceptance field messes up the regex and the classes `wpcf7-checkbox form-check-input` get added, which messes up the bootstrap layout. 

adding an additional 
`$content = preg_replace('/wpcf7-checkbox form-check-input/i', '', $content);` solves the problem. In my project it seems to solve the problem. Maybe someone can test it further for sideeffect. If there is no problem I would contribute a PR

**Comment by crftwrk** [comment]
Thank you! Yes, it would be great if you create a PR for this.
